### ISSUE TITLE
imputation error

### ISSUE THREAD

**Issue by rkb965** [stekhoven/missForest#20]
For the returned OOB error, is there any general guidance on when there is too much error to likely be useful? Even if data- and context-dependent, I do not know how to interpret the NMRSE and the PFC, and I would grateful appreciate any resources to guide decisions with regard to these measures.

**Comment by stekhoven** [comment]
The best way to better understand the error measures is to run missForest in supervised mode, i.e. provide `xtrue` and see what kind of errors appear. If your data contains missing values from the start, select a portion of it which is fully observed an generate some artificial missing values using `prodNA()` and use this as `xmis` while the fully observed part is used as `xtrue`. However, as you say - the error rates are context dependent.
