### ISSUE TITLE
Question on data imputation for well data

### ISSUE THREAD

**Issue by ivan-marroquin** [stekhoven/missForest#22]
Hi,

I read with great interest the paper by Stekhoven and Buehlmann: MissForest - nonparametric missing value imputation for mixed-type data.

I am new into this type of analysis and I would like to know if missForest can be applied to my data. I work with logging data (continuous and discrete). The missing information can be caused by geologic conditions, drilling operations, and/or logging costs. Since these conditions are external to actual data measurements, I believe the missing data follow a MCAR model. Therefore, the number of data points from one well to the next may vary, and this cause vectors of unequal length. In the sketch in the zip file, I show the issue of having vectors of unequal length. 

As you can see from the sketch, the missing data is towards the tail of the recorded data. Given such characteristic, is still possible to apply missForest to replace missing values?

Many thanks for your help,

Ivan

[Missing_data_distribution.zip](https://github.com/stekhoven/missForest/files/4476485/Missing_data_distribution.zip)

**Comment by stekhoven** [comment]
Yes, it will. However, we expect the variables to be dependent of each other. If you plug the data in like that, the method will think that the measurements within one row are one observation, thus it will use the values in wells D, E and F to predict the remaining wells in row 7. If this is the case, go ahead.
If the measurements for the different wells are independent or if the measurements in one row are at different time points, you might want to consider melting the data set into long format. Like so:

```
time | well | measurement
-----------------------------
1    | A    | 1.63 
1    | B    | 1.84
1    | C    | 1.25
...
1    | I    | 1.92
2   | A    | 1.23
2   | B    | 2.01
...
4    | C    | NA
4    | D    | 173
...
```
