### ISSUE TITLE
Problems with using csv files

### ISSUE THREAD

**Issue by 2902** [stekhoven/missForest#24]
Hi! 
I'm learning how to use missForest and did the exercises of the tutorial ---> https://stat.ethz.ch/education/semesters/ss2012/ams/paper/missForest_1.2.pdf

While exploring how this program works, I exported the dataframe with missing data from the tutorial as an csv file with:
   data(iris)
   iris.mis <- prodNA(iris, noNA = 0.1) # Adding missing data at random
   write.csv(iris.mis,"iris.mis.csv", row.names = FALSE)

Later I imputed the exported file in a new R file:
  i.m<-read.csv("iris.mis.csv")

I tried running a simple imputation "i.m" and it displayed an error:
  iris.imp1 <- missForest(i.m)

   argument is not numeric or logical: returning NA  missForest iteration 1 in progress...
   Error in randomForest.default(x = obsX, y = obsY, ntree = ntree, mtry = mtry, : NA not permitted in predictors

I don't understand why I am having this problem since both "iris.mis" and "i.m" look the same. Is NA being interpreted differently in i.m because I imported it as an csv file?

I did this test, because I'm having a similar problem with my own dataset that is a csv file. The difference is that I deal with categorical and binary data. The error is:
   D.imp <- missForest(D)
   argument is not numeric or logical: returning NA  missForest iteration 1 in progress...done!
   Error in ximp[, t.ind] - ximp.old[, t.ind] : 
    non-numeric argument to binary operator

Hope somebody knows how to solve this issue,

2902

**Comment by bgall** [comment]
Almost certainly a case of strings being treated as factors in one case and not the other.

**Comment by stekhoven** [comment]
What @bgall describes is most likely what happened. 

When exporting and importing the modes of some variables can be changed/lost. If a variable with 'strings' is considered numeric by R, the above error message will be returned.
