### ISSUE TITLE
prevent printing of iterations

### ISSUE THREAD

**Issue by markvanderloo** [stekhoven/missForest#6]
It would be nice if the option `verbose=FALSE` would also prevent printing of the iteration count to the command-line. Or perhaps, `verbose` could have three levels?

Thanks for considering!
best,
-M

**Comment by markvanderloo** [comment]
I ran into this again, and maybe I should clarify why I would like this feature. It has mainly to do with being able to suppress printed output in the context of document generation like in `rmarkdown` or `Sweave`.

**Comment by stekhoven** [comment]
I have change the behaviour of verbose accordingly. 
Setting verbose=FALSE now suppresses also the printing of the iterations.
